<template>
    <div>
        <h1>Photography: From Passion to Profession</h1>
        <h3>M Aminur Rahman</h3>
        <h4>Chief Photographer, Checkmate Events<br>CEO, NOMAD Digital</h4>
        <p>Human by nature, are passion driven. Think of a new born, in their toddler years, whatever they do, everyone cheers them up, every single move is welcomed with immense joy, every small step forward is recorded. As time passes by, priorities change, we are chasing that inevitable dream of maintaining social standards but where does passion lie by? Most of us, are lost in the race of life, we bury our passion and led by a life set up by the societal standards. A person without passion is a body without soul. How do we pursue the deepest desire among us?</p>
        <p>Photography, by nature is intriguing. It demands engagement, a science of combining sub-conscious brain to an advanced technical machine. We are talking about mixing art and science here. Photography demands precision, it requires attention at a time from a daily life, an escape route of our soul into the massive possibilities of visual art creation. The question remains, are we passionate enough to pursue photography.</p>
        <p>Many of us come close to a camera while we are approaching our juvenile years. Fast forward 20 years back, even in the early 2000s a film camera, very basic, say a KODAK, was a part of family functions usually operated by the energetic kids of the family. That thrill of developing a film from negative might not be available due to advancement of technology but it still remains to the core, composition of an extraordinary image from what others merely see as a scene. How many of us are actually pursuing that juvenile dream of a family photographer in a film camera / a cell phone photographer / camera operator of a cousin of fnf’s rented camera? What are we afraid of.</p>
        <p>Bangladesh is a land of opportunities, the principal nature is we are a set of homogeneous people living in a small area, uplifting the same culture and speaking the same language. Name any corporation, always willing to do business in Bangladesh. Then why not a photographer living up his dream job as a profession? What’s holding them back?</p>
        <p>To embrace an inner passion as a profession, we often do the mistake of chasing for expensive gears, choosing who’d be our mentor, fighting over brands, criticising others while we forget the most important part. An artist is born from the inside, the connection of heart and brain that multiplies into the number of arts they produce in their own lifespan. To be courageous to take photography as a profession, the first step is to build thyself from the scratch. Be prepared for all the bashing, people won’t believe on your dreams, take the positives from the questions. You have the answers stored in your head, you know that path to greatness, better to answer your critiques by your success, be open to suggestions, take positives from in and around you, develop yourself as an artist first.</p>
        <p>Not to forget the basics, once that initial journey of tormenting yourself, I call it metamorphosis of an artist, improve your skillset. Learn everyday, search for the techniques you want to enhance in your arsenal. Be open to working opportunities, forget about money for some time, be an intern to the industry professionals. Wake up everyday, stop scrolling the social media, learn a new thing in YouTube. Enhance your philosophy, be a better photographer everyday. Don’t be shy to enrol in workshops, remember a penny spent in learning is way more collective than spending in your GAS (Gear Acquisition Syndrome).</p>
        <p>You have completed the basic steps now it’s time to reflect in the outer world. Relieve yourself from the temptation of just another social media page with low budget options, your work should speak for yourselves and let your suiters set the price for you. Avoid free assignments at this period. Work with other professionals and set up a primary team. Not only taking photographs but presenting them in an eye catching manner, market your potential to the seekers of better photography. Your online and offline presence is very important to shine your creative skills among the competitors. One Pro Tip : Start early. If you’ve started developing yourself as a photographer as early as completing your higher secondary, you’d have an experience of 12 years by the time you are 30.</p>
        <p>Stop wasting time, rather than make it work for you. Make every meeting a fruitful one by discussing possibilities and opportunities. Embrace every technological advancement to be up to date. A photographer of 21st century is an allrounder. Do not forget to sharpen other necessary skills around. Your connections are your prime asset. Networking is the key to success. Never stop learning, do not hesitate to take new challenges, do not underperform your potential.</p>
        <p>Success takes time to accommodate. We have a new morning everyday, we have a chance to start afresh as soon as the sun rises. Be humble, be grateful. Be passionate about photography. Do not abuse the prime craft of visual imagery, it’s a gift from Almighty. The power of creation, harnessing the prospect of being an artist, not everyone is blessed. Embrace all the difficulties of taking an alternative career. Be loyal to your goal, the return will be enormous.</p>
        <p>Your journey to greatness awaits. Break the norm, be the bravest, live the life of a successful photographer.</p>
    </div>
</template>